// CUTSCENE RECRUTEMENT

// SI QUETE DES ESCLAVES TERMINEE
// HENDAK RECRUTABLE

IF
  True()
THEN
  RESPONSE #100
    CutSceneId(Player1)
    Wait(1)
    FadeToColor([20.0],0)
    Wait(1)
    ActionOverride("Hendak",DestroySelf())
    CreateCreature("HB#Henda",[592.1238],0)
    JumpToPoint([589.1275])
    FaceObject("HB#Henda")
    MoveViewObject(Myself,INSTANT)
    SetGlobal("HB#EnfantsLiberes","GLOBAL",2)
    Wait(1)
    FadeFromColor([20.0],0)
    Wait(1)
    ActionOverride("HB#Henda",StartDialogueNoSet(Player1))
    EndCutSceneMode()
END



