IF
     See(NearestEnemyOf(Myself))
     HaveSpell(WIZARD_MISLEAD)
     HaveSpell(WIZARD_MIRROR_IMAGE)
     HaveSpell(WIZARD_FIRE_SHIELD_BLUE)
     Global("HB#CombatM","GLOBAL",0)

THEN
    RESPONSE #100

      ReallyForceSpell(Myself,WIZARD_MISLEAD)
      ReallyForceSpell(Myself,WIZARD_MIRROR_IMAGE)
      ReallyForceSpell(Myself,WIZARD_FIRE_SHIELD_BLUE)
      SetGlobal("HB#CombatM","GLOBAL",1)
END

IF
	See(NearestEnemyOf(Myself))
	HaveSpell(WIZARD_SYMBOL_DEATH)
THEN
	RESPONSE #100
		Spell(NearestEnemyOf(Myself),WIZARD_SYMBOL_DEATH)
END

IF
	See(NearestEnemyOf(Myself))
	HaveSpell(WIZARD_ABI_DALZIMS_HORRID_WILTING)
THEN
	RESPONSE #100
		Spell(NearestEnemyOf(Myself),WIZARD_ABI_DALZIMS_HORRID_WILTING)
END

IF
	See(NearestEnemyOf(Myself))
	HaveSpell(WIZARD_PRISMATIC_SPRAY)
THEN
	RESPONSE #100
		Spell(NearestEnemyOf(Myself),WIZARD_PRISMATIC_SPRAY)
END

IF
	See(NearestEnemyOf(Myself))
	HaveSpell(WIZARD_FINGER_OF_DEATH)
THEN
	RESPONSE #100
		Spell(NearestEnemyOf(Myself),WIZARD_FINGER_OF_DEATH)
END

IF
	See(NearestEnemyOf(Myself))
	HaveSpell(WIZARD_FLESH_TO_STONE)
THEN
	RESPONSE #100
		Spell(NearestEnemyOf(Myself),WIZARD_FLESH_TO_STONE)
END

IF
	See(NearestEnemyOf(Myself))
	HaveSpell(WIZARD_GREATER_MALISON)
THEN
	RESPONSE #100
		Spell(NearestEnemyOf(Myself),WIZARD_GREATER_MALISON)
END


IF
	See(NearestEnemyOf(Myself))
	HaveSpell(WIZARD_HOLD_PERSON)
THEN
	RESPONSE #100
		Spell(NearestEnemyOf(Myself),WIZARD_HOLD_PERSON)
END

IF
	See(NearestEnemyOf(Myself))
	HaveSpell(WIZARD_MISLEAD)
THEN
	RESPONSE #100
		Spell(Myself,WIZARD_MISLEAD)
END


IF
	See(NearestEnemyOf(Myself))
	HaveSpell(WIZARD_MELF_ACID_ARROW)
THEN
	RESPONSE #100
		Spell(NearestEnemyOf(Myself),WIZARD_MELF_ACID_ARROW)
END

IF
	See(NearestEnemyOf(Myself))
	HaveSpell(WIZARD_MELF_ACID_ARROW)
THEN
	RESPONSE #100
		Spell(NearestEnemyOf(Myself),WIZARD_MELF_ACID_ARROW)
END

IF
	See(NearestEnemyOf(Myself))
	HaveSpell(WIZARD_MAGIC_MISSILE)
THEN
	RESPONSE #100
		Spell(NearestEnemyOf(Myself),WIZARD_MAGIC_MISSILE)
END

IF
	See(NearestEnemyOf(Myself))
	HaveSpell(WIZARD_MAGIC_MISSILE)
THEN
	RESPONSE #100
		Spell(NearestEnemyOf(Myself),WIZARD_MAGIC_MISSILE)
END

IF
	See(NearestEnemyOf(Myself))
	HaveSpell(WIZARD_LARLOCH_MINOR_DRAIN)
THEN
	RESPONSE #100
		Spell(NearestEnemyOf(Myself),WIZARD_LARLOCH_MINOR_DRAIN)
END

IF
	See(NearestEnemyOf(Myself))
	HaveSpell(WIZARD_LARLOCH_MINOR_DRAIN)
THEN
	RESPONSE #100
		Spell(NearestEnemyOf(Myself),WIZARD_LARLOCH_MINOR_DRAIN)
END